# Generated by Django 6.0.1 on 2026-02-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-create'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
    ]
